Object subclass: #DRGateAND
	instanceVariableNames: 'locationX locationY'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'DigitalRepository'!

!DRGateAND methodsFor: 'accessing' stamp: 'mh 5/12/2010 01:33:59.218'!
locationX
	^ locationX! !

!DRGateAND methodsFor: 'accessing' stamp: 'mh 5/12/2010 01:33:59.311'!
locationX: anObject
	locationX := anObject! !

!DRGateAND methodsFor: 'accessing' stamp: 'mh 5/12/2010 01:33:59.355'!
locationY
	^ locationY! !

!DRGateAND methodsFor: 'accessing' stamp: 'mh 5/12/2010 01:33:59.392'!
locationY: anObject
	locationY := anObject! !
